### ISSUE TITLE
能否增加对条件表达式的支持？

### ISSUE THREAD

**Issue by dusdong** [toolgood/ToolGood.Algorithm#1]
比如：6>4 and 3>2  或者 6>4 && 3>2，这样书写 要比 And(6>4,3>2) 的方式 ，更人性化一些

**Comment by toolgood** [comment]
抱歉，这个类库主要是依据excel公式语法来的，所以不支持

**Comment by dusdong** [comment]
好的，我改造下试试。感谢您的开源项目！
