### ISSUE TITLE
days360 not correct 

### ISSUE THREAD

**Issue by lyk12** [toolgood/ToolGood.Algorithm#13]
Hi,

days360(date(2020,5,31),date(2023,12,15)) not working.
in the projection, code "new DateTime(startMyDate.Year, startMyDate.Month + 1, 1).AddDays(-1).Day)" should change to "new DateTime(startMyDate.Year, startMyDate.Month, 1).AddMonths(1).AddDays(-1).Day"

thanks,
lyk

**Comment by toolgood** [comment]
This problem has been fixed!
