### ISSUE TITLE
未能加载文件或程序集“Antlr4.Runtime.Standard”或它的某一个依赖项

### ISSUE THREAD

**Issue by seeseasonjack** [toolgood/ToolGood.Algorithm#17]
我使用.NET FRAMEWORK 4.7 的 MVC默认项目，添加NUGET包，后运行就报错，应该是版本问题，我换成 4.11的版本后，运行不报错，可是解析报错，似乎是版本里方法不对了，请求支援，非常感谢。以下是报错信息：

未能加载文件或程序集“Antlr4.Runtime.Standard”或它的某一个依赖项。未能验证强名称签名。此程序集可能已被篡改，或者已被延迟签名，但没有用正确的私钥进行完全签名。 (异常来自 HRESULT:0x80131045)
说明: 执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。

异常详细信息: System.IO.FileLoadException: 未能加载文件或程序集“Antlr4.Runtime.Standard”或它的某一个依赖项。未能验证强名称签名。此程序集可能已被篡改，或者已被延迟签名，但没有用正确的私钥进行完全签名。 (异常来自 HRESULT:0x80131045)

**Comment by toolgood** [comment]
下载最新版本
