### ISSUE TITLE
提议：ToolGood.Algorithm 合并ToolGood.FlowVision 中的ToolGood.Algorithm2

### ISSUE THREAD

**Issue by toolgood** [toolgood/ToolGood.Algorithm#25]
ToolGood.Algorithm2 与 ToolGood.Algorithm 工程上的扩展，包括了长度、重量、体积换算
Extension of ToolGood.Algorithm2 and ToolGood.Algorithm engineering, including length, weight, and volume conversions

当默认 “长度单位”为米 
When the default 'length unit' is meters
当默认 “面积单位”为平方米
When the default 'area unit' is square meters
当默认 “体积单位”为立方米
When the default 'volume unit' is cubic meters
当默认 “重量单位”为千克
When the default 'weight unit' is kilogram

可以设置以下公式   The following formula can be set 
```
if(length > 50cm,1,0)

if(area <=25m2,1,0)

if(weight >50kg,1,0)

if(weight >5t,1,0)

```

主要原因还是我懒，不想同时维护两套代码。
 The main reason is that I am lazy and do not want to maintain two sets of code at the same time.

**Comment by toolgood** [comment]
@ZhangBohan @zhengqiang1988 @seeseasonjack  @lyk12  @suichuan @dusdong

**Comment by ZhangBohan** [comment]
ToolGood.Algorithm2是一个新项目吗，这个提议没看懂

**Comment by toolgood** [comment]
不是，ToolGood.Algorithm2是ToolGood.Algorithm的一个分支，为了开发工作流而建的一个分支，现在想合并到ToolGood.Algorithm

**Comment by ZhangBohan** [comment]
要提个MR一起Review下吗

**Comment by toolgood** [comment]
我现在建一个分支`v3.5`，过几天，代码会更新到分支`v3.5`
https://github.com/toolgood/ToolGood.Algorithm/tree/v3.5

到时大家看一下，影响不大的。

**Comment by toolgood** [comment]
功能上增加一些东西

**Comment by toolgood** [comment]
代码已更新到`v3.5`分支上，

主要改动：
1、添加GETPARAMETER方法 ：可以动态获取参数
2、添加Error方法: 用于主动抛错
3、添加 `{ }` 用于定于 json格式  {k1:v1,k2:v2 } 或 数组 {1,2,3,4,"333"}
4、添加 hasKey 和 hasValue  用于   json和 数组 
5、单位转化功能，长度，面积、体积、重量
6、java版本 BigDecimal 精度问题 ，为了绝大部分的正确， 比较前将精度缩小到12位再进行比较
          例：计算公式 `1=0.001*1000`  未修改返回 false，这个是有问题的。
7、修改部分错误代码。

**Comment by toolgood** [comment]
`AlgorithmEngineHelper`类 增加 `UnitConversion` 方法，用于数值的单位转换
