### ISSUE TITLE
日期操作有1秒差异

### ISSUE THREAD

**Issue by sickle12138** [toolgood/ToolGood.Algorithm#27]
`DATE(YEAR(NOW()), MONTH(NOW()), 1) + TIME(8, 0, 0)`
输出2024-08-01 07:5959
调用环境java17
`<groupId>io.github.toolgood</groupId>
<artifactId>toolgood-algorithm</artifactId>
<version>3.5.0.1</version>`

**Comment by toolgood** [comment]
已修复，更新一下包吧
