### ISSUE TITLE
碰到一个非常罕见的问题：由于CurrentThread.CurrentUICulture 为非 zh-CN 引起的错误

### ISSUE THREAD

**Issue by dusdong** [toolgood/ToolGood.Algorithm#3]
测试代码如下：

```
//设置非 zh-cn 语言
Thread.CurrentThread.CurrentCulture = new CultureInfo("fr-FR");
Thread.CurrentThread.CurrentUICulture = new CultureInfo("fr-FR");

value = engine.TryEvaluate("0.0000 <= 1", false);
Assert.AreEqual(value, true);
```

在 fr-FR 的情况，0.0000 无法正确转换为 double 类型，导致公式计算出错

**Comment by toolgood** [comment]
是.net 底层出错了，详见 https://github.com/dotnet/corefx/issues/41356

**Comment by toolgood** [comment]
“”“
I was going to suggest this was because in fr-FR the decimal separator is a comma. But in en-US, 0,000 parses successfully.
”“”

法语的小数点是逗号。

**Comment by dusdong** [comment]
我竟然碰到了 .net 底层的bug，也是够我吹几年的牛皮的了，哈哈。

可是，他们怎么把你的issue关了，不给修复吗？

**Comment by toolgood** [comment]
他们认为这不是bug....,不需要修正。

**Comment by toolgood** [comment]
更新了代码，修复了法语数字转化的问题
